name: Deploy Cognishop Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1
      with:
        host: 62.72.56.173
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd cognishop/supersearch-backend/
          # Fetch the latest deploy.sh from origin before running it
          git fetch origin
          git checkout origin/main -- deploy.sh
          bash deploy.sh 