name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: 62.72.56.173
        username: root
        password: wDQC2za1L9jmafj@
        script: |
          cd cognishop/supersearch-backend/
          bash deploy.sh 